---
- name: Verify
  hosts: haproxy
  tasks:

    - name: Verify systemd service is running
      ansible.builtin.systemd:
        name: haproxy
        state: started
      check_mode: true
      register: systemd_check
      failed_when: false

    - name: Assert systemd is active
      ansible.builtin.assert:
        that:
          - systemd_check is not failed
        fail_msg: "Systemd service not running"

    - name: Ensure we can reach the webserver through HAproxy
      ansible.builtin.uri:
        url: http://localhost
        return_content: yes
      register: result
      until: result.status == 200
      retries: 5
      delay: 1